baseURL = "https://ranco-disaster.netlify.com/"
enableRobotsTXT = true
languageCode = "en-us"
theme = "site-theme"
title = "Ranco Response"
[mediaTypes."text/noExt"]
suffixes = ""
[[menu.desktop]]
identifier = "Contact Us"
name = "Contact Us"
url = "/contact-us/"
weight = 7
[[menu.desktop]]
identifier = "About Us"
name = "About Us"
url = "/about-us/"
weight = 6
[[menu.desktop]]
identifier = "Amenities"
name = "Amenities"
url = "/amenities/"
weight = 5
[[menu.desktop]]
identifier = "Structures"
name = "Structures"
url = "/structures/"
weight = 4
[[menu.desktop]]
identifier = "Event Support"
name = "Event Support"
url = "/event-support/"
weight = 3
[[menu.desktop]]
identifier = "Logistics Support"
name = "Logistics Support"
url = "/logistics-support/"
weight = 2
[[menu.desktop]]
identifier = "Emergency Response"
name = "Emergency Response"
url = "/emergency-response/"
weight = 1
[[menu.footer]]
identifier = "Showers"
name = "Showers"
parent = "Amenities"
url = "/amenities/#showers"
weight = 8
[[menu.footer]]
identifier = "Sinks"
name = "Sinks"
parent = "Amenities"
url = "/amenities/#sinks"
weight = 7
[[menu.footer]]
identifier = "Wrap-Around Services"
name = "Wrap-Around Services"
parent = "Emergency Response"
url = "/wrap-around-services/"
weight = 7
[[menu.footer]]
identifier = "Tents / Shelters 1"
name = "Tents / Shelters"
parent = "Logistics Support"
url = "/structures/"
weight = 6
[[menu.footer]]
identifier = "Toilets"
name = "Toilets"
parent = "Amenities"
url = "/amenities/#toilets"
weight = 6
[[menu.footer]]
identifier = "Tents / Shelters"
name = "Tents / Shelters"
parent = "Emergency Response"
url = "/structures/"
weight = 6
[[menu.footer]]
identifier = "Event Spaces"
name = "Event Spaces"
parent = "Structures"
url = "/structures/#event-br-spaces"
weight = 6
[[menu.footer]]
identifier = "Tents / Shelters 2"
name = "Tents / Shelters"
parent = "Event Support"
url = "/structures/"
weight = 6
[[menu.footer]]
identifier = "Life Support Areas"
name = "Life Support Areas"
parent = "Structures"
url = "/structures/#life-support-areas"
weight = 5
[[menu.footer]]
identifier = "Laundry"
name = "Laundry"
parent = "Amenities"
url = "/amenities/#laundry"
weight = 5
[[menu.footer]]
identifier = "LSA Support"
name = "LSA Support"
parent = "Emergency Response"
url = "/lsa-support/"
weight = 5
[[menu.footer]]
identifier = "LSA Support 1"
name = "LSA Support"
parent = "Logistics Support"
url = "/lsa-support/"
weight = 5
[[menu.footer]]
identifier = "LSA Support 2"
name = "LSA Support"
parent = "Event Support"
url = "/lsa-support/"
weight = 5
[[menu.footer]]
identifier = "Kitchens"
name = "Kitchens"
parent = "Amenities"
url = "/amenities/#kitchens"
weight = 4
[[menu.footer]]
identifier = "Business Continuity"
name = "Business Continuity"
parent = "Emergency Response"
url = "/business-continuity/"
weight = 4
[[menu.footer]]
identifier = "Business Continuity 2"
name = "Business Continuity"
parent = "Event Support"
url = "/business-continuity/"
weight = 4
[[menu.footer]]
identifier = "Business Continuity 1"
name = "Business Continuity"
parent = "Logistics Support"
url = "/business-continuity/"
weight = 4
[[menu.footer]]
identifier = "Extreme Weather"
name = "Extreme Weather"
parent = "Structures"
url = "/structures/#extreme-weather"
weight = 4
[[menu.footer]]
identifier = "Tactical Operations Center 1"
name = "Tactical Operations Center"
parent = "Logistics Support"
url = "/tactical-operations-centers/"
weight = 3
[[menu.footer]]
identifier = "Tactical Operations Center"
name = "Tactical Operations Center"
parent = "Emergency Response"
url = "/tactical-operations-centers/"
weight = 3
[[menu.footer]]
identifier = "Construction & Maintainance"
name = "Construction & Maintenance"
parent = "Structures"
url = "/structures/#construction-covers"
weight = 3
[[menu.footer]]
identifier = "Tactical Operations Center 2"
name = "Tactical Operations Center"
parent = "Event Support"
url = "/tactical-operations-centers/"
weight = 3
[[menu.footer]]
identifier = "HVAC & Dehumidification"
name = "HVAC & Dehumidification"
parent = "Amenities"
url = "/amenities/#hvac"
weight = 3
[[menu.footer]]
identifier = "Turn-key Camps"
name = "Turn-key Camps"
parent = "Emergency Response"
url = "/turnkey-camps/"
weight = 2
[[menu.footer]]
identifier = "Turn-key Camps 1"
name = "Turn-key Camps"
parent = "Logistics Support"
url = "/turnkey-camps/"
weight = 2
[[menu.footer]]
identifier = "Turn-key Camps 2"
name = "Turn-key Camps"
parent = "Event Support"
url = "/turnkey-camps/"
weight = 2
[[menu.footer]]
identifier = "Lighting"
name = "Lighting"
parent = "Amenities"
url = "/amenities/#lighting"
weight = 2
[[menu.footer]]
identifier = "Warehouse & Storage"
name = "Warehouse & Storage"
parent = "Structures"
url = "/structures/#warehouse-storage"
weight = 2
[[menu.footer]]
identifier = "Power"
name = "Power"
parent = "Amenities"
url = "/amenities/#power"
weight = 1
[[menu.footer]]
identifier = "Facilities Support 1"
name = "Facilities Support"
parent = "Logistics Support"
url = "/facilities-support/"
weight = 1
[[menu.footer]]
identifier = "Facilities Support"
name = "Facilities Support"
parent = "Emergency Response"
url = "/facilities-support/"
weight = 1
[[menu.footer]]
identifier = "Lunch & Break Areas"
name = "Lunch & Break Areas"
parent = "Structures"
url = "/structures/#lunch-and-break-areas"
weight = 1
[[menu.footer]]
identifier = "Facilities Support 2"
name = "Facilities Support"
parent = "Event Support"
url = "/facilities-support/"
weight = 1
[[menu.footer]]
identifier = "Amenities"
name = "Amenities"
weight = 5
[[menu.footer]]
identifier = "Structures"
name = "Structures"
url = "/structures/"
weight = 4
[[menu.footer]]
identifier = "Event Support"
name = "Event Support"
weight = 3
[[menu.footer]]
identifier = "Logistics Support"
name = "Logistics Support"
weight = 2
[[menu.footer]]
identifier = "Emergency Response"
name = "Emergency Response"
weight = 1
[[menu.mobile]]
identifier = "Who we are"
name = "Who we are"
url = "/about-us/"
weight = 6
[[menu.mobile]]
identifier = "Amenities"
name = "Amenities"
url = "/amenities/"
weight = 5
[[menu.mobile]]
identifier = "Structures"
name = "Structures"
url = "/structures/"
weight = 4
[[menu.mobile]]
identifier = "Event Support"
name = "Event Support"
url = "/event-support/"
weight = 3
[[menu.mobile]]
identifier = "Logistics Support"
name = "Logistics Support"
url = "/logistics-support/"
weight = 2
[[menu.mobile]]
identifier = "Emergency Response"
name = "Emergency Response"
url = "/emergency-response/"
weight = 1
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true
[outputFormats.redirects]
baseName = "_redirects"
isPlainText = true
mediaType = "text/noExt"
path = "/"
[outputFormats.sitemapindex]
baseName = "sitemapindex"
isPlainText = false
mediaType = "application/xml"
path = "/"
[outputFormats.sitepages]
baseName = "sitepages"
isPlainText = false
mediaType = "application/xml"
path = "/"
[outputFormats.siteposts]
baseName = "siteposts"
isPlainText = false
mediaType = "application/xml"
path = "/"
[outputs]
home = ["HTML", "sitemapindex", "sitepages", "siteposts", "RSS", "redirects", "Algolia"]
[params.algolia]
appId = ""
indexName = ""
searchKey = ""
[params.extraTools]
algoliaSearch = false
floatingHeader = false
fontAwesome = true
[params.publishingSettings]
siteinProduction = true
[params.socialLinks]
facebook = ""
insta = ""
linkedin = ""
pinterest = ""
[params.tracking]
cloudinary_url = "https://res.cloudinary.com/pioneer-design/image/upload"
[params.utilityImages]
thankyouBackground = ""
[sitemap]
filename = "sitepages.xml"
